name = "Big Gay Neoforge"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2395b2060ec1a46cdab5c45e89601a2fe9332f73dc32ce707461cd54665a5e78"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
