name = "Big Gay Neoforge"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d627356b1cedbc36cd460e8568218888c1c293b313c372ba184a2a361d9a248"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
