name = "Big Gay Neoforge"
author = "consume"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adb1caff908a33ab8129a00b26007af95a4b1a16c9456dd26b215cd7230bc0f8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.224"
